root@leechbane:/home/jon/example-frontend# pwd
/home/jon/example-frontend
root@leechbane:/home/jon/example-frontend# ls
dockerfile  package.json  package-lock.json  public  README.md  src
root@leechbane:/home/jon/example-frontend# cat dockerfile
FROM ubuntu

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN apt update -y && apt install curl -y
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt install -y nodejs
RUN npm install
RUN npm run build
RUN npm install -g serve

CMD ["serve", "-s", "-l", "5000", "build"]
root@leechbane:/home/jon/example-frontend# docker build . -t example-frontend && docker run -p 5000:5000 example-frontend