root@leechbane:/home/jon/spring-example-project# pwd
/home/jon/spring-example-project
root@leechbane:/home/jon/spring-example-project# ls
dockerfile  mvnw  mvnw.cmd  pom.xml  README.md  src
root@leechbane:/home/jon/spring-example-project# cat dockerfile
FROM openjdk:8

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

RUN ./mvnw package

CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]
root@leechbane:/home/jon/spring-example-project#
root@leechbane:/home/jon/spring-example-project# docker build . -t spring-example-project && docker run -p 8080:8080 spring-example-project
